"""
Marcbantu Africa — PDF Service.
Generates printable HTML for reports (client converts to PDF).
"""
from utils import now_iso


class PDFService:
    def __init__(self, env):
        self.env = env

    def _base_styles(self) -> str:
        return """
        <style>
            * { box-sizing: border-box; }
            body { font-family: 'Segoe UI', Arial, sans-serif; color: #1e2a1e; margin: 0; padding: 40px; }
            .header { border-bottom: 3px solid #d4a017; padding-bottom: 15px; margin-bottom: 25px; }
            .header h1 { color: #1a3c2e; margin: 0 0 4px; font-size: 24px; }
            .header .sub { color: #666; font-size: 13px; }
            .section { margin-bottom: 30px; }
            .section h2 { color: #1a3c2e; font-size: 16px; border-bottom: 1px solid #e2e8dd; padding-bottom: 6px; margin-bottom: 12px; }
            table { width: 100%; border-collapse: collapse; font-size: 13px; }
            th { background: #e8f0e1; color: #1a3c2e; text-align: left; padding: 8px; }
            td { padding: 8px; border-bottom: 1px solid #e2e8dd; }
            .kpi { display: flex; gap: 20px; margin-bottom: 20px; }
            .kpi-box { flex: 1; padding: 15px; border: 1px solid #e2e8dd; border-left: 4px solid #d4a017; border-radius: 6px; }
            .kpi-box .label { font-size: 11px; color: #666; text-transform: uppercase; }
            .kpi-box .value { font-size: 20px; font-weight: bold; color: #1a3c2e; margin-top: 4px; }
            .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #e2e8dd; font-size: 11px; color: #888; text-align: center; }
            .positive { color: #2e7d32; }
            .negative { color: #c0392b; }
        </style>
        """

    def _header(self, title: str, subtitle: str = "") -> str:
        return f"""
        <div class="header">
            <h1>Marcbantu Africa</h1>
            <div class="sub">{title} — {subtitle or now_iso()[:10]}</div>
        </div>
        """

    def _footer(self) -> str:
        return f"""
        <div class="footer">
            Generated by Marcbantu Africa on {now_iso()[:10]} · marcbantu.africa
        </div>
        """

    def _kpi(self, label: str, value: str, cls: str = "") -> str:
        return f"""
        <div class="kpi-box">
            <div class="label">{label}</div>
            <div class="value {cls}">{value}</div>
        </div>
        """

    def profit_loss_pdf(self, report: dict, farmer_name: str = "") -> str:
        """Return printable HTML for a P&L statement."""
        s = report.get("summary", {})
        period = report.get("period", {})
        net = s.get("net_profit", 0)
        net_cls = "positive" if net >= 0 else "negative"

        income_rows = "".join(
            f"<tr><td>{r['item']}</td><td>{r['count']}</td><td>KES {r['amount']:,.2f}</td></tr>"
            for r in report.get("income", [])
        )
        expense_rows = "".join(
            f"<tr><td>{r['item']}</td><td>{r['count']}</td><td>KES {r['amount']:,.2f}</td></tr>"
            for r in report.get("expenses", [])
        )

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Profit & Loss</title>{self._base_styles()}</head>
<body>
{self._header("Profit & Loss Statement", f"{period.get('from')} to {period.get('to')}")}
{f'<p style="color:#666;font-size:13px;">Prepared for: <strong>{farmer_name}</strong></p>' if farmer_name else ''}
<div class="kpi">
    {self._kpi("Total Income", f"KES {s.get('total_income', 0):,.2f}")}
    {self._kpi("Total Expenses", f"KES {s.get('total_expenses', 0):,.2f}")}
    {self._kpi("Net Profit", f"KES {net:,.2f}", net_cls)}
    {self._kpi("Margin", f"{s.get('margin_percent', 0)}%")}
</div>
<div class="section"><h2>Income</h2>
<table><thead><tr><th>Category</th><th>Count</th><th>Amount</th></tr></thead><tbody>{income_rows}</tbody></table>
</div>
<div class="section"><h2>Expenses</h2>
<table><thead><tr><th>Category</th><th>Count</th><th>Amount</th></tr></thead><tbody>{expense_rows}</tbody></table>
</div>
{self._footer()}
</body></html>"""

    def enterprise_performance_pdf(self, report: dict, farmer_name: str = "") -> str:
        """Printable enterprise comparison report."""
        rows = "".join(
            f"<tr><td>{e.get('rank')}</td><td>{e['enterprise']}</td>"
            f"<td>{e['type']}</td>"
            f"<td>KES {e['income']:,.2f}</td>"
            f"<td>KES {e['expenses']:,.2f}</td>"
            f"<td class=\"{'positive' if e['profit'] >= 0 else 'negative'}\">KES {e['profit']:,.2f}</td>"
            f"<td>{e['margin_percent']}%</td>"
            f"<td>{e['roi_percent']}%</td></tr>"
            for e in report.get("enterprises", [])
        )
        best = report.get("best_performer") or {}
        worst = report.get("worst_performer") or {}

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Enterprise Performance</title>{self._base_styles()}</head>
<body>
{self._header("Enterprise Performance", f"{report.get('period', {}).get('from')} to {report.get('period', {}).get('to')}")}
{f'<p style="color:#666;font-size:13px;">Prepared for: <strong>{farmer_name}</strong></p>' if farmer_name else ''}
<div class="section"><h2>All Enterprises</h2>
<table><thead>
<tr><th>Rank</th><th>Enterprise</th><th>Type</th><th>Income</th><th>Expenses</th><th>Profit</th><th>Margin</th><th>ROI</th></tr>
</thead><tbody>{rows}</tbody></table>
</div>
<div class="section"><h2>Summary</h2>
<p><strong>Best performer:</strong> {best.get('enterprise', '—')} ({best.get('profit', 0):,.0f} KES)</p>
<p><strong>Needs review:</strong> {worst.get('enterprise', '—')} ({worst.get('profit', 0):,.0f} KES)</p>
</div>
{self._footer()}
</body></html>"""

    def credit_report_pdf(self, score_data: dict, farmer_name: str = "") -> str:
        s = score_data.get("score", 0)
        rating = score_data.get("rating", "—")
        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Credit Score Report</title>{self._base_styles()}</head>
<body>
{self._header("Farm Credit Score Report")}
{f'<p style="color:#666;font-size:13px;">Prepared for: <strong>{farmer_name}</strong></p>' if farmer_name else ''}
<div class="kpi">
    {self._kpi("Score", str(s))}
    {self._kpi("Rating", rating)}
    {self._kpi("Recommended Loan Limit", f"KES {score_data.get('recommended_loan_limit', 0):,.0f}")}
</div>
<div class="section"><h2>Score Components</h2>
<table><thead><tr><th>Component</th><th>Points</th></tr></thead><tbody>
{''.join(f"<tr><td>{k.replace('_',' ').title()}</td><td>{v}</td></tr>" for k, v in (score_data.get('components') or {}).items())}
</tbody></table>
</div>
<div class="section"><h2>Metrics</h2>
<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>
{''.join(f"<tr><td>{k.replace('_',' ').title()}</td><td>{v}</td></tr>" for k, v in (score_data.get('metrics') or {}).items())}
</tbody></table>
</div>
<p style="font-size:12px;color:#888;">{score_data.get('note', '')}</p>
{self._footer()}
</body></html>"""